report/urls.py
"""
%% urls.py %%

This file define the urls used in the software for tcc application. In this regular expression are used, which are used to connect the url with the functions defined.
"""

#::::::::::::::IMPORT THE HEADER FILE HERE::::::::::::::::::::::::::::::#
from django.conf.urls.defaults import *
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()
from result_generator.report.models import *
from result_generator.report.views import *
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#

#:::::::::::::::DEFINE THE URLS HERE::::::::::::::::::::::::::::::::::::#

urlpatterns = patterns('result_generator.report.views',
	(r'^newstudent/$', 'new_student'),
	(r'^search/$', 'search'),
	(r'^addmarks/$', 'add_marks'),
	(r'^add_activities/$', 'add_activities'),
	(r'^seltype/$', 'sel_type'),
	(r'^addresult/$', 'add_result'),
	(r'^gen_res/$', 'marks_fill'),
	(r'^add_skills/$', 'add_skills'),
   #(r'^publishers/$', PublisherDetail.as_view()),
)

urls.py
"""
%% urls.py %%

This file is define the main url for the Software. It links the software with different applications.
"""

#::::::::::::::IMPORT THE HEADER FILE HERE::::::::::::::::::::::::::::::#
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib import admin
admin.autodiscover()
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#

#:::::::::::::::DEFINE THE URLS HERE::::::::::::::::::::::::::::::::::::#


urlpatterns = patterns('',
    (r'^$', 'result_generator.report.views.index'),
	(r'^report/', include('result_generator.report.urls')),
    (r'^admin/', include(admin.site.urls)),
   
)

report/models.py
"""
%% models.py %%
This file contains all the defination for models of Auto software. 
including tables, classes, forms and mappers.
"""

#::::::::::::::IMPORT THE HEADER FILE HERE:::::::::::::::::::::::::::::#
from result_generator.report.header import *
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#

#::::::::::::::::::::::DEFINE THE MODELS HERE:::::::::::::::::::::::::::#
class Organisation(models.Model):
	"""
	** Organisation **
	
	Organisation Class define all fields required to submit detail 
	about Organisation.
	
	""" 
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=150)
	phone = models.CharField(max_length=20)
	director = models.CharField(max_length=50) 
	status = models.CharField(max_length=5000)
	logo_upload = models.ImageField(upload_to='logo')

	def __unicode__(self):
        	return self.name
    
class Class(models.Model):
	name = models.CharField(max_length=100)

	def __unicode__(self):
        	return self.name
        	    	
class Student(models.Model):
	
	name = models.CharField(max_length=200)
	std = models.ForeignKey(Class)
	reg_no = models.IntegerField()
	roll_no = models.IntegerField()
	father_name = models.CharField(max_length=200)
	mother_name = models.CharField(max_length=200)
	address = models.CharField(max_length=1000)
	dob = models.CharField(max_length=200)
	phone_no = models.CharField(max_length=200)
	
	def __unicode__(self):
        	return self.name
        	
class StudentForm(ModelForm):
	
	class Meta :
		model = Student
	
	widgets = {
		'name' : TextInput(attrs={'size':60}),
		'std' : TextInput(attrs={'size':60}),
		'reg no.' : TextInput(attrs={'size':60}),
		'address' : TextInput(attrs={'size':60}),
		'roll_no' : TextInput(attrs={'size':60}),
		'father_name' : TextInput(attrs={'size':60}),
		'mother_name' : TextInput(attrs={'size':60}),
		'dob' : TextInput(attrs={'size':60}),
		'phone_no' : TextInput(attrs={'size':60}),
		
                  }

class Subjects(models.Model):
	name = models.CharField(max_length=100)
	
	def __unicode__(self):
        	return self.name


class Tests(models.Model):
	name = models.CharField(max_length=100)

	def __unicode__(self):
        	return self.name
	

class Maxmarks(models.Model):
	test = models.ForeignKey(Tests)
	clas = models.ForeignKey(Class)
	q_eng = models.IntegerField()
	a_eng = models.CharField(max_length=200)
	q_pun = models.IntegerField()
	a_pun = models.CharField(max_length=200)
	q_sst = models.IntegerField()
	a_sst = models.CharField(max_length=200)
	q_sci = models.IntegerField()
	a_sci = models.CharField(max_length=200)
	q_math = models.IntegerField()
	a_math = models.CharField(max_length=200)
	q_comp = models.IntegerField()
	a_comp = models.CharField(max_length=200)
	q_draw = models.IntegerField()
	a_draw = models.CharField(max_length=200)
	q_m_oral = models.IntegerField()
	a_m_oral = models.CharField(max_length=200)
	
class FAtest(models.Model):
	student = models.ForeignKey(Student)
	test = models.ForeignKey(Tests)
	q_eng = models.FloatField(default="0.0")
	a_eng = models.CharField(max_length=200,default="0,0,0,0,0")
	q_pun = models.FloatField(default="0.0")
	a_pun = models.CharField(max_length=200,default="0,0,0,0,0")
	q_sst = models.FloatField(default="0.0")
	a_sst = models.CharField(max_length=200,default="0,0,0,0,0")
	q_sci = models.FloatField(default="0.0")
	a_sci = models.CharField(max_length=200,default="0,0,0,0,0")
	q_math = models.FloatField(default="0.0")
	a_math = models.CharField(max_length=200,default="0,0,0,0,0")
	q_comp = models.FloatField(default="0.0")
	a_comp = models.CharField(max_length=200,default="0,0,0,0,0")
	q_draw = models.FloatField(default="0.0")
	a_draw = models.CharField(max_length=200,default="0,0,0,0,0")
	q_m_oral = models.FloatField(default="0.0")
	a_m_oral = models.CharField(max_length=200,default="0,0,0,0,0")

class FAtestForm(ModelForm):
	class Meta :
		model = FAtest
		exclude= ['test',]
	
	
class FAresult(models.Model):
	fatest = models.OneToOneField(FAtest)
	max3_eng = models.CharField(max_length=20,blank=True,null=True)
	marks_eng = models.FloatField(blank=True,null=True)
	total_eng = models.FloatField(blank=True,null=True)
	max3_pun = models.CharField(max_length=20,blank=True,null=True)
	marks_pun = models.FloatField(blank=True,null=True)
	total_pun = models.FloatField(blank=True,null=True)
	max3_sst = models.CharField(max_length=20,blank=True,null=True)
	marks_sst = models.FloatField(blank=True,null=True)
	total_sst = models.FloatField(blank=True,null=True)
	max3_sci = models.CharField(max_length=20,blank=True,null=True)
	marks_sci = models.FloatField(blank=True,null=True)
	total_sci = models.FloatField(blank=True,null=True)
	max3_math = models.CharField(max_length=20,blank=True,null=True)
	marks_math = models.FloatField(blank=True,null=True)
	total_math = models.FloatField(blank=True,null=True)
	max3_comp = models.CharField(max_length=20,blank=True,null=True)
	marks_comp = models.FloatField(blank=True,null=True)
	total_comp = models.FloatField(blank=True,null=True)
	max3_draw = models.CharField(max_length=20,blank=True,null=True)
	marks_draw = models.FloatField(blank=True,null=True)
	total_draw = models.FloatField(blank=True,null=True)
	max3_m_oral = models.CharField(max_length=20,blank=True,null=True)
	marks_m_oral = models.FloatField(blank=True,null=True)
	total_m_oral = models.FloatField(blank=True,null=True)
	
class SAtest(models.Model):
	student = models.ForeignKey(Student)
	test = models.ForeignKey(Tests)
	q_eng = models.FloatField(default="0.0")
	q_pun = models.FloatField(default="0.0")
	q_sst = models.FloatField(default="0.0")
	q_sci = models.FloatField(default="0.0")
	q_math = models.FloatField(default="0.0")
	q_comp = models.FloatField(default="0.0")
	q_draw = models.FloatField(default="0.0")
	q_m_oral = models.FloatField(default="0.0")
	
class SAtestForm(ModelForm):
	class Meta :
		model = SAtest
		exclude= ['test',]

class SAresult(models.Model):
	fatest = models.OneToOneField(SAtest)
	marks_eng = models.FloatField(blank=True,null=True)
	total_eng = models.FloatField(blank=True,null=True)
	marks_pun = models.FloatField(blank=True,null=True)
	total_pun = models.FloatField(blank=True,null=True)
	marks_sst = models.FloatField(blank=True,null=True)
	total_sst = models.FloatField(blank=True,null=True)
	marks_sci = models.FloatField(blank=True,null=True)
	total_sci = models.FloatField(blank=True,null=True)
	marks_math = models.FloatField(blank=True,null=True)
	total_math = models.FloatField(blank=True,null=True)
	marks_comp = models.FloatField(blank=True,null=True)
	total_comp = models.FloatField(blank=True,null=True)
	marks_draw = models.FloatField(blank=True,null=True)
	total_draw = models.FloatField(blank=True,null=True)
	marks_m_oral = models.FloatField(blank=True,null=True)
	total_m_oral = models.FloatField(blank=True,null=True)
	
class ThinkingSkills(models.Model):
	student = models.ForeignKey(Student)
	skill1 = models.FloatField(default="0.0")
	skill2  = models.FloatField(default="0.0")
	skill3  = models.FloatField(default="0.0")
	skill4  = models.FloatField(default="0.0")
	skill5  = models.FloatField(default="0.0")
	skill6  =  models.FloatField(default="0.0")
	skill7  = models.FloatField(default="0.0")
	skill8  = models.FloatField(default="0.0")
	skill9  = models.FloatField(default="0.0")
	skill10  = models.FloatField(default="0.0")
	
class ThinkingSkillsForm(ModelForm):
	
	class Meta :
		model = ThinkingSkills
		
	skill1 = forms.FloatField(label='Knows his or her strengths and weaknesses')
	skill2 = forms.FloatField(label='Demonstrates internal or external locus of control')
	skill3 = forms.FloatField(label='Knows his or her way of dealing with people events and things')
	skill4 = forms.FloatField(label='Recognizes and analyzes a problem')
	skill5 = forms.FloatField(label='Collects relevant information from reliable sources')
	skill6 = forms.FloatField(label='Evaluates each alternative for advantageous and adverse consequences of each alternative situation')
	skill7 = forms.FloatField(label='Chooses the best alternative shows originality and innovation')
	skill8 = forms.FloatField(label='Demonstrates fluency in ideas get lots of new ideas')
	skill9 = forms.FloatField(label='Open to modification and flexibility in thinking')
	skill10 = forms.FloatField(label='Demonstrates divergent thinking')
		
class SocialSkills(models.Model):
	student = models.ForeignKey(Student)
	skill1 = models.FloatField(default="0.0")
	skill2 = models.FloatField(default="0.0")
	skill3 = models.FloatField(default="0.0")
	skill4 = models.FloatField(default="0.0")
	skill5 = models.FloatField(default="0.0")
	skill6 = models.FloatField(default="0.0")
	skill7 = models.FloatField(default="0.0")
	skill8 = models.FloatField(default="0.0")
	skill9 = models.FloatField(default="0.0")
	skill10 = models.FloatField(default="0.0")
	
class SocialSkillsForm(ModelForm):
	
	class Meta :
		model = SocialSkills
		
	skill1 = forms.FloatField(label='Helps classmates in case of difficulties in academic and personal issues')
	skill2 = forms.FloatField(label='Seeks feedback from teachers and peers for self improvement')
	skill3 = forms.FloatField(label='Actively listens and pays attention of others when speaking in the class school assembly and other occasions')
	skill4 = forms.FloatField(label='Sees and appreciates others point of view')
	skill5 = forms.FloatField(label='Draws attention of others when speaking in the class school assembly and other occasions')
	skill6 = forms.FloatField(label='Explains and articulates a concept differently so that others can understand in simple language')
	skill7 = forms.FloatField(label='Sensitive to the needs of differently abled students')
	skill8 = forms.FloatField(label='Demonstates leadership skills like responsibility initiative etc')
	skill9 = forms.FloatField(label='Demonstrates awareness of norms and social conduct and follows them')

report/forms.py
from django import forms
from django.forms import ModelChoiceField
from result_generator.report.models import *

class SelectType(forms.Form):
	std = forms.ModelChoiceField(queryset=Class.objects.all()) 
	test = forms.ModelChoiceField(queryset=Tests,objects.all()) 

templates/report/add_activities.html
{% extends base_template|default:"base.html" %} 
{% load i18n %} 
<html>
{% block content %} 
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Result Generator</title>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
  // Code adapted from http://djangosnippets.org/snippets/1389/

  function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+-)');
    var replacement = prefix + '-' + ndx + '-';
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
 replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
  }

  function deleteForm(btn, prefix) {
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());

    if (formCount > 1) {
      // Delete the item/form
      $(btn).parents('.item').remove();

      var forms = $('.item'); // Get all the forms

      // Update the total number of forms (1 less than before)
      $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);

      var i = 0;
      // Go through the forms and set their indices, names and IDs
      for (formCount = forms.length; i < formCount; i++) {
        $(forms.get(i)).children().children().each(function() {
          updateElementIndex(this, prefix, i);
        });
      }

    } // End if
    else {
        alert("You have to enter at least one todo item!");
    }
    return false;
  }


  function addForm(btn, prefix) {
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());

    // You can only submit a maximum of 30 todo items 
    if (formCount < 30) {
      // Clone a form (without event handlers) from the first form
      var row = $(".item:first").clone(false).get(0);
      // Insert it after the last form
      $(row).removeAttr('id').hide().insertAfter(".item:last").slideDown(300);
      
      // Remove the bits we don't want in the new row/form
      // e.g. error messages
      $(".errorlist", row).remove();
      $(row).children().removeClass('error');
      
      // Relabel/rename all the relevant bits
      $(row).children().children().each(function() {
        updateElementIndex(this, prefix, formCount);
        if ( $(this).attr('type') == 'text' )
          $(this).val('');
      });
      
      // Add an event handler for the delete item/form link 
      $(row).find('.delete').click(function() {
        return deleteForm(this, prefix);
      });

      // Update the total form count
      $('#id_' + prefix + '-TOTAL_FORMS').val(formCount + 1); 

    } // End if
    else {
      alert("Sorry, you can only enter a maximum of ten items.");
    }
    return false;
  }

  // Register the click event handlers
  $("#add").click(function() {
    return addForm(this, 'form');
  });
  
  $(".delete").click(function() {
    return deleteForm(this, 'form');
  });


});
</script>

<link href='style.css' rel='stylesheet' type='text/css'><link href='{{ MEDIA_URL }}calendar/datepick/redmond.datepick.css' rel='stylesheet' type='text/css'><script type='text/javascript' src='{{ MEDIA_URL }}calendar/datepick/jquery.datepick.js'></script><script>
 $(document).ready(function(){
   $('#id_Date_of_testing').datepick({dateFormat:'yyyy-mm-dd'});
 });
 </script>

</head>
<body>

<h1>Add Activities</h1>


<form action="" method="POST">{% csrf_token %}
  	
    {{ activity_formset.management_form }}
    {% for form in activity_formset.forms %}
    <div class="item">
		{{ form.as_p }}
		<p style=""><a class="delete" href="#">Delete</a></p>  
	</div>
    {% endfor %}
    <p><a id="add" href="#">Add Row</a></p>

    <input type="submit" value=" Submit " />

</form>

</body>
</html>
{% endblock %}

templates/report/add_marks.html
{% extends base_template|default:"base.html" %}
{% load i18n %}
<html>
<head>
    <title>{{school.name}}</title>
</head>
{% block content %}

<h1> Student form</h1>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
	{% csrf_token %}
        <table width="100%">
            {{ form.as_table }}
        </table>
        
        	<input type="submit" value="Submit">
     		<input type="button" value="Home" onClick="location.href='/res_generator/'">
    </form>
   
</html>
{% endblock %}

templates/report/marks_filled.html
{% extends "base.html" %}
{% load i18n %}
<html lang="en">
<head>
    <title>Form filled</title>
</head>
{% block content %}

<h1 >Form filled</h1>  
<table>
<tr>

<input type="button" value="Continue adding the result for same student" onClick="javascript:history.go(-2);">

		<input type="button" value="Done" onClick="http://localhost/result/">
	</tr>	
		</table>
</body>
{% endblock %}

templates/report/marks_ok.html
{% extends "base.html" %}
{% load i18n %}

<html>
<head>
    <title>{{school.name}}</title>
</head>
{% block content %}
<body>
Thanks, for Adding marks <br/>
<br/><br/>

	
</table>


</body>
{% endblock %}

templates/report/result.html
{% extends "base.html" %}
{% load i18n %}
<html lang="en">
<head>
    <title>Result</title>
</head>
{% block content %}

<h1 >Result</h1>          

<table border="1" width="100%">
<tr>
		<th>Marks Obtained</th>
        <th>Total Marks</th>
        <th>Percentage</th>
        <th>Marks</th>
        <th>Marks Percentage</th>
	
	</tr>

	<tr>
	
        <td> {{ marks }}</td>
        <td> {{results.maxmarks}}</td>
        <td>{{results.perc}}</td>
        <td>{{results.faperc}}</td>
        <td>{{results.totalperc}}</td>

	</tr>
  
</table>

</html>
{% endblock %}

templates/report/search_results.html
{% extends "base.html" %}
{% load i18n %}
<html lang="en">
<head>
    <title>Search</title>
</head>
{% block content %}
<form action="." method="GET">
<h1 >Search a Student</h1>          
<label for="id_q">Search:</label>
<input id="id_q" name="q" type="text"><br>
<input type="submit" value="Submit">

 </form>
 <br>
You searched for "{{ query_string }}" and the results are listed below.
<table border="1" width="100%">
<tr>
		<th>Sr.No </th>
		<th>Name of Student</th>
                <th>Address</th>
                <th>Roll No.</th>
               
                <th>Phone No</th>
	
		<th>Your Activity</th>
	</tr>
{% if found_entries %}
  {% for client in found_entries %}
	<tr>
	<td>{{forloop.counter}}</td>
        <td> {{ client.name }}</td>
        <td> {{client.address}}</td>
        <td>{{client.roll_no}}</td>
        <td>{{client.phone_no}}</td>
       

       <td><a href="/result/school/addmarks/?id={{client.id}}">ADD RESULT</a></td>
	
	</tr>
      {% endfor %}
      </ul>
    {% else %}
      No Students found
    {% endif %}
</table>

</html>
{% endblock %}

templates/report/select_type.html
{% extends base_template|default:"base.html" %}
{% load i18n %}
<html>
	<head>
		<title>{{title.name}}</title>
	</head>

{% block content %}
	
	<h2 class="changeBlue">Add Result</h2>
	<form method="GET" action="http://localhost/res_generator/report/addresult/" onsubmit="alert(action+'?'+'class'+'='+class.value+'&'+'test'+'='+test.value);return true;">
<table>
	
 <tr>
 	<td><label for="id_search">Class:</label></td>
 	<td><select name="class">
		<option value="">________</option>
			{% for class in clas %}
  				<option value="{{class.id}}">{{class.name}}</option>
			{% endfor %}
		</select>
		
	</td>
	<td><label for="id_test">Tests:</label></td>
	<td><select name="test">
		<option value="">________</option>
			{% for tests in test %}
  				<option value="{{tests.id}}">{{tests.name}}</option>
			{% endfor %}
		</select>
	</td>
 </table>
 	<input type="submit">
		</form>	
			
</div>
</html>
{% endblock %}

templates/report/student.html
{% extends base_template|default:"base.html" %}
{% load i18n %}
<html>
<head>
    <title>{{school.name}}</title>
</head>
{% block content %}

<h1> Student form</h1>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
	{% csrf_token %}
        <table width="100%">
            {{ form.as_table }}
        </table>
        
        	<input type="submit" value="Submit">
     
    </form>
   
</html>
{% endblock %}

templates/report/student_ok.html
{% extends "base.html" %}
{% load i18n %}

<html>
<head>
    <title>{{school.name}}</title>
</head>
{% block content %}
<body>
Thanks, for Adding Student <br/>
<br/><br/>

	
</table>


</body>
{% endblock %}